### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by akabab** [akabab/tetris#1]
# TODOS

### learning
- [ ] learn [redux](http://redux.js.org/) with [videos](https://egghead.io/lessons/javascript-redux-the-single-immutable-state-tree)

### setups
- [ ] setup [prettier-eslint](https://github.com/prettier/prettier-eslint)
- [ ] setup [code coverage](https://github.com/avajs/ava/blob/master/docs/recipes/code-coverage.md)

### doc
- [tuto](https://github.com/jonhoo/tetris-tutorial)
- [rotation patterns](http://tetris.wikia.com/wiki/SRS)

### exemples
- [chvin/react-tetris](https://github.com/chvin/react-tetris)
- [gcedo/react-tetris](https://github.com/gcedo/react-tetris)
- [brandly/react-tetris](https://github.com/brandly/react-tetris)
